[package]
name = "quark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { path = "../../", default-features = true }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }