name: Main Workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  DISCORD_ENV_TOKEN: ${{ secrets.DISCORD_ENV_TOKEN }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["stable"]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build Binary
        run: cargo build

      - name: Build Release Binary
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: cargo build --release

      - name: Run Unit Tests
        run: cargo test --verbose

      - name: Run Release Unit Tests
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: cargo test --release --verbose
